### ISSUE TITLE
How to replicate a pnpm-lock.yaml with serde-yaml-ng

### ISSUE THREAD

**Issue by SamTV12345** [acatton/serde-yaml-ng#9] opened 2024-09-19 21:07 UTC
Hi I'd like to write a package manager or already have a somewhat working package manager but I don't want to have a fight between pnpm and my package manager that is why I want to have my pm to also generate an identical pnpm-lock.yaml so that it doesn't matter which tool you use. 

Do you know how I can insert custom newlines in my yaml. There are two edge cases:

Most of the things are separated by newlines:

yaml
```
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      is-even:
        specifier: ^1.0.0
        version: 1.0.0
    devDependencies:
      eslint:
        specifier: ^7.2.0
        version: 7.32.0
```

and there is this resolution info that is for whatever reason inline

  '@babel/code-frame@7.12.11':
    resolution: {integrity: sha512-Zt1yodBx1UcyiePMSkWnU4hPqhwq7hGi2nFL1LeA3EUl+q2LQx16MISgJ0+z7dnmgvP9QtIleuETGOiOH1RcIw==}
    
 Is there some way to tell serde or your library to do this formating?

**Comment by acatton** [comment] 2024-09-19 21:21
Hi there,

`serde-yaml-ng` is the continuation of [`serde-yaml`](https://github.com/dtolnay/serde-yaml) which was just a [serde](https://serde.rs/) wrapper around [LibYAML](https://pyyaml.org/wiki/LibYAML). LibYAML does the heavy lifting, I would recommend you read its code (or, more accurately, the [transpiled version](https://github.com/dtolnay/unsafe-libyaml) used by `serde-yaml-ng`) to get the answer to your question.

This is a bug tracker, not a support forum. I'll close this issue since, AFAIT, it's not describing any bug or unintended behaviour. Good places to get community support are [stackoverflow.com](https://stackoverflow.com) and [users.rust-lang.org](https://users.rust-lang.org).

[Thank you for your understanding](https://github.com/acatton/serde-yaml-ng/blob/c4903d7fe059acec011af38e539f5baa9723bacd/README.md#why) :)

**Closed by acatton** 2024-09-19 21:21 UTC
